//UI components
import { Label } from "@/components/ui/label"
import { ScrollArea } from "@/components/ui/scroll-area"

export const GameRules = () => {
    return (
        <div>
            <Label className="text-2xl">Game rules</Label>
            <div className="">
                <ScrollArea className="p-2 w-[21vw] h-[40vh] bg-white rounded-lg border-[1px] border-gray-300">
                    <h4>Online Mastermind: Game Rules</h4>
                    <br />

                    <h5>Objective</h5>
                    <p className="font-normal text-lg">The goal of Online Mastermind is to crack the secret code generated by the system within a limited number of attempts using logic and deduction.</p>
                    <br />

                    <h5>Game Setup</h5>
                    <ul className="list-disc list-inside">
                        <li>The code is randomly generated by the system.</li>
                        <li>The player selects the number of pegs (4–7) and whether colors can repeat.</li>
                        <li>A digital notepad is available for jotting down thoughts and patterns.</li>
                    </ul>
                    <br />

                    <h5>Gameplay</h5>
                    <ol className="list-decimal pl-5">
                        <li>Make a Guess: Select a sequence of pegs in the available slots.</li>
                        <li>Receive Feedback: The system provides clues:
                            <ul className="list-disc pl-5">
                                <li><strong>Black peg</strong> = A correct color in the correct position.</li>
                                <li><strong>White peg</strong> = A correct color in the wrong position.</li>
                                <li><strong>No peg</strong> = That color is not in the code.</li>
                            </ul>
                        </li>
                        <li>Use Notes: Write down observations, patterns, or strategies to track progress.</li>
                        <li>Winning & Losing:
                            <ul className="list-disc pl-5">
                                <li><strong>You win</strong> if you guess the exact combination within the allowed attempts.</li>
                                <li><strong>You lose</strong> if you fail to guess the code before running out of turns.</li>
                            </ul>
                        </li>
                    </ol>

                </ScrollArea>
            </div>
        </div>
    )
}